version: '3'

services:
  jenkins-master:
    container_name: jenkins
    image: jenkins-as-code:test
    ports:
      - "8080:8080"
    environment:
      - JENKINS_ADMIN_ID
      - JENKINS_ADMIN_PASSWORD
    networks:
      - jenkins-net

networks:
  jenkins-net:
