pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/PheaSoy/spring-boot-kubernetes'
            }
        }
        stage('SAST') {
            steps {
                echo "Testing"
            }
        }
        stage('SCA') {
            steps {
                echo "Deploying"
            }
        }
    }
}
