pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/rivera-bl/spring-boot-kubernetes'
            }
        }
        stage('SonarCloud') {
          environment {
            SCANNER_HOME = tool 'SonarQubeScanner'
            ORGANIZATION = "rivera-bl"
            PROJECT_NAME = "spring-boot-kubernetes"
            SONAR_TOKEN = "243b286caeaee9a5802593ecdfdc8b7e99507e20"
          }
          steps {
            withSonarQubeEnv('SonarCloudURL') {
                sh '''$SCANNER_HOME/bin/sonar-scanner -Dsonar.organization=$ORGANIZATION \
                -Dsonar.java.binaries=.mvn/wrapper/ \
                -Dsonar.projectKey=$PROJECT_NAME \
                -Dsonar.sources=.'''
            }
          }
        }
        stage('SCA') {
            steps {
                echo "Deploying"
            }
        }
    }
}
