pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/rivera-bl/spring-boot-kubernetes'
            }
        }
        stage('SonarCloud') {
          environment {
            SCANNER_HOME = tool 'SonarQubeScanner'
            ORGANIZATION = "rivera-bl"
            PROJECT_NAME = "spring-boot-kubernetes"
            SONAR_TOKEN = "4e7dcf0da5356c275b337b4ebaeff93b834dd9f5"
          }
          steps {
            withSonarQubeEnv('SonarCloudURL') {
                sh '''$SCANNER_HOME/bin/sonar-scanner -Dsonar.organization=$ORGANIZATION \
                -Dsonar.java.binaries=.mvn/wrapper/ \
                -Dsonar.projectKey=$PROJECT_NAME \
                -Dsonar.sources=.'''
            }
          }
        }
        stage('SCA') {
            steps {
                echo "Deploying"
            }
        }
    }
}
